apiVersion: apps/v1
kind: Deployment
metadata:
  name: certvault-deployment
  labels:
    app: certvault-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: certvault-app
  template:
    metadata:
      labels:
        app: certvault-app
    spec:
      containers:
        - name: certvault-app-deployment
          image: cr.yandex/crpsk48ocfqquoto4qeo/cert-vault:bacaa877b65073a132efc3a14c5b83bca0787881
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000