spring:
  application:
    name: hometask6-security
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:hometask6
    driver-class-name: org.h2.Driver
    username: root
    password: KaKaDu-2106
  h2:
    console:
      enabled: true

encryption:
  charset: UTF-8
  key: aesEncryptionKey
  algorithm: AES
  initVector: encryptionIntVec
  transformation: AES/CBC/PKCS5PADDING

