#cloud-config
runcmd:
  - wget -O - https://monitoring.api.cloud.yandex.net/monitoring/v2/unifiedAgent/config/install.sh | bash
datasource:
  Ec2:
    strict_id: false
ssh_pwauth: no
users:
  - name: ${YC_VM_USERNAME}
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${YC_VM_SSH}
