#cloud-config
runcmd:
  - mkdir /run/yc
  - "curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh > /run/yc/install.sh"
  - [ sudo, bash, /run/yc/install.sh]
  - [ sudo, mkdir, /data ]
  - "sudo /root/yandex-cloud/bin/yc lockbox payload get --id e6qd1rqko2qtg45sdtkr --key POSTGRES_LOGIN > export POSTGRES_LOGIN"
  - "sudo /root/yandex-cloud/bin/yc lockbox payload get --id e6qd1rqko2qtg45sdtkr --key POSTGRES_PASSWORD > export POSTGRES_PASSWORD"
datasource:
  Ec2:
    strict_id: false
ssh_pwauth: no
users:
  - name: {{env.YC_VM_USERNAME}}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - {{env.YC_VM_SSH}}
