#cloud-config
runcmd:
  - "mkdir /run/yc"
  - "curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh > /run/yc/install.sh"
  - [ sudo, bash, /run/yc/install.sh]
  - "export POSTGRES_LOGIN=$(yc lockbox payload get --id e6qd1rqko2qtg45sdtkr --key POSTGRES_LOGIN)"
  - "export POSTGRES_PASSWORD=$(yc lockbox payload get --id e6qd1rqko2qtg45sdtkr --key POSTGRES_PASSWORD)"
output: {all: '| tee -a /var/log/cloud-init-output.log'}
datasource:
  Ec2:
    strict_id: false
ssh_pwauth: no
users:
  - name: {{env.YC_VM_USERNAME}}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - {{env.YC_VM_SSH}}
