name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Execute maven build
        run: mvn clean package
      - name: Docker Image Building
        run: docker build --build-arg JAR_FILE=target/\*.jar . --tag cr.yandex/crpbqprflma7cocaik4p/cert-vault:${{github.sha}}
      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}    
      - name: Docker Image Pushing
        run: docker push cr.yandex/crpbqprflma7cocaik4p/cert-vault:${{github.sha}}
      - name: Latest Docker Image
        if: github.ref == 'refs/heads/main'
        run: docker tag cr.yandex/crpbqprflma7cocaik4p/cert-vault:${{github.sha}} cr.yandex/crpbqprflma7cocaik4p/cert-vault:latest && docker push cr.yandex/crpbqprflma7cocaik4p/cert-vault:latest  
